CREATE DATABASE SUPERMERCADO;
GO
USE SUPERMERCADO;

CREATE TABLE ESTADO(
ID_ESTADO INT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(35)
);

CREATE TABLE CIUDAD(
ID_CIUDAD INT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(35),
ID_ESTADO INT REFERENCES ESTADO(ID_ESTADO)
);

CREATE TABLE SUCURSAL(
ID_SUCURSAL INT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(35),
DIRECCION VARCHAR(35),
TELEFONO INT,
ID_CIUDAD INT REFERENCES CIUDAD(ID_CIUDAD)
);

CREATE TABLE DEPARTAMENTO(
ID_DEPTO INT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(35),
DESCRIPCION VARCHAR(50),
ID_SUCURSAL INT REFERENCES SUCURSAL(ID_SUCURSAL)
);

CREATE TABLE PROMOCION(
ID_PROMOCION INT NOT NULL PRIMARY KEY,
DESCRIPCION VARCHAR(35),
TIPO_PROMO VARCHAR(35),
DURACION INT
);

CREATE TABLE CAJERO(
ID_CAJERO INT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(35),
TIPO_CAJERO VARCHAR(20)
);

CREATE TABLE PROVEEDOR(
ID_PROVEEDOR INT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(35)
);

CREATE TABLE PRODUCTO(
ID_PRODUCTO INT NOT NULL PRIMARY KEY,
SKU VARCHAR(35),
NOMBRE VARCHAR(35),
DESCRIPCION VARCHAR(35),
CANTIDAD INT,
COSTO DECIMAL(10,2),
FECHA_INGRESO DATE,
FECHA_EGRESO DATE,
PRECIO_GANANCIA DECIMAL(10,2),
ID_PROVEEDOR INT REFERENCES PROVEEDOR(ID_PROVEEDOR)
);

CREATE TABLE SUCURSAL_PRODUCTO(
ID_PRODUCTO INT PRIMARY KEY REFERENCES PRODUCTO(ID_PRODUCTO),
ID_SUCURSAL INT REFERENCES SUCURSAL(ID_SUCURSAL),
CAPACIDAD_PROD DECIMAL(10,2),
CAPACIDAD_ASIGNADA DECIMAL(10,2)
);

CREATE TABLE PROMOCION_SUCURSAL_PRODUCTO(
ID_PROMOCION INT PRIMARY KEY REFERENCES PROMOCION(ID_PROMOCION),
ID_SUCURSAL INT REFERENCES SUCURSAL(ID_SUCURSAL),
ID_PRODUCTO INT REFERENCES PRODUCTO(ID_PRODUCTO),
FECHA_INICIO DATE,
FECHA_FIN DATE,
TIPO_PROMOCION VARCHAR(35),
PRECIO_ESPECIAL DECIMAL(10,2),
DESCUENTO DECIMAL(10,2)
);

CREATE TABLE VENTA_ENCA(
ID_VENTA INT NOT NULL PRIMARY KEY,
ID_SUCURSAL INT REFERENCES SUCURSAL(ID_SUCURSAL),
ID_CAJERO INT REFERENCES CAJERO(ID_CAJERO),
TIPO_VENTA VARCHAR(35), 
TOTAL DECIMAL(10,2),
FECHA_VENTA DATE
);

CREATE TABLE VENTA_DETA(
ID_VENTA INT NOT NULL PRIMARY KEY REFERENCES VENTA_ENCA(ID_VENTA),
ID_PRODUCTO INT REFERENCES PRODUCTO(ID_PRODUCTO),
CANTIDAD INT,
COSTO_UNITARIO DECIMAL(10,2),
SUBTOTAL_COST DECIMAL(10,2),
CODIGO_CUPON_PROMO INT,
MONTO_DESCUENTO DECIMAL(10,2),
SUBTOTAL_DESCUENTO DECIMAL(10,2)
);

--TABLA DE HECHOS TRANSACCIONAL SOBRE VENTAS
CREATE TABLE HECHO_VENTA(
ID_VENTA INT,
ID_PRODUCTO INT,
ID_SUCURSAL INT,
DIRECCION_SUCURSAL VARCHAR(35),
ID_CAJERO INT,
TIPO_VENTA VARCHAR(35),
TOTAL DECIMAL(10,2),
FECHA_VENTA DATE,
CANTIDAD INT,
COSTO_UNITARIO DECIMAL(10,2),
SUBTOTAL_COST DECIMAL(10,2),
CODIGO_CUPON_PROMO INT,
MONTO_DESCUENTO DECIMAL(10,2),
SUBTOTAL_DESCUENTO DECIMAL(10,2)
);

--SNAPSHOT INVENTARIO
CREATE TABLE INVENTARIO(
ID_PRODUCTO INT,
SKU VARCHAR(35),
NOMBRE VARCHAR(35),
DESCRIPCION VARCHAR(35),
CANTIDAD INT,
COSTO DECIMAL(10,2),
ID_PROVEEDOR INT,
FECHA_INGRESO DATE,
FECHA_EGRESO DATE,
PRECIO_GANANCIA DECIMAL(10,2),
ID_SUCURSAL INT
);